name: Build, Test, and Deploy to NuGet on Push
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore ./src/Ebooks.ProfanityDetector.sln
    - name: Build
      run: dotnet build ./src/Ebooks.ProfanityDetector.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/Ebooks.ProfanityDetector.sln --no-restore --verbosity normal
    - name: Nerdbank.GitVersioning
      id: nbgv
      uses: dotnet/nbgv@v0.3.1
    - name: Publish Ebooks.ProfanityDetector to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PACKAGE_NAME: Ebooks.ProfanityDetector
        VERSION_STATIC: ${{ steps.nbgv.outputs.NuGetPackageVersion }}
        PROJECT_FILE_PATH: src/ProfanityDetector/Ebooks.ProfanityDetector.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
    - name: Publish Ebooks.ProfanityDetector.Extensions to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PACKAGE_NAME: Ebooks.ProfanityDetector.Extensions
        VERSION_STATIC: ${{ steps.nbgv.outputs.NuGetPackageVersion }}
        PROJECT_FILE_PATH: src/Ebooks.ProfanityDetectorExtensions/Ebooks.ProfanityDetector.Extensions.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}